### ISSUE TITLE
Merge partnerwebsite with cms

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/partners.ubuntu.com#105]
Why are there two applications, `partnerwebsite` and `cms`, inside this project?

We should consolidate into one called `webapp`, as with our other projects.

**Comment by nottrobin** [comment]
I successfully moved and switched all the files over in [this branch](https://github.com/nottrobin/partners.ubuntu.com/tree/105-consolidate-in-webapp). It works, as long as you start from a fresh database.

The problem is that with an existing database that was created using the old `cms.models`, many references clash. I'm not sure how to fix this right now. We'll need to think about it.

**Comment by WillMoggridge** [comment]
Is a solution like this, something that can help?
https://docs.djangoproject.com/en/1.10/howto/writing-migrations/#migrating-data-between-third-party-apps

**Comment by nottrobin** [comment]
@WillMoggridge yep I'd say that looks like the right sort of solution. We'd need to experiment.
