### ISSUE TITLE
Logo block not working correctly

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/partners.ubuntu.com#108]
## Summary

Setting a partner to the OpenStack programme and setting the "always featured" flag doesn't dislplay the partner on http://partners.ubuntu.com/programmes/openstack; this should be the case.

**Comment by deadlight** [comment]
@nottrobin We're getting chased about a fix for this. Can we take a look at it together tomorrow?

**Comment by nottrobin** [comment]
@deadlight why wait until tomorrow?

**Comment by deadlight** [comment]
@nottrobin: I might have some time today. Feel free if you're free :)

**Comment by pmahnke** [comment]
I can confirm that this happens on local as well... so NOT a caching issue.

**Comment by pmahnke** [comment]
[Launchpad bug](https://bugs.launchpad.net/ubuntu-website-content/+bug/1673514) relates
