### ISSUE TITLE
Lenovo logo in homepage is out of date

### ISSUE THREAD

**Issue by fitojb** [canonical-websites/partners.ubuntu.com#114]
The Lenovo logo that is featured below the section “A selection of Ubuntu partners” is outdated. They changed it [in 2015](http://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_lenovo_by_saatchi_saatchi_new_york.php).

**Comment by pmahnke** [comment]
@fitojb 

thanks for filing the issue.

this is fixed now

![image](https://cloud.githubusercontent.com/assets/441217/24035399/4cd5a174-0aed-11e7-9391-5b122ae77e55.png)


Peter
