### ISSUE TITLE
Partner order in Finder not alphabetic

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/partners.ubuntu.com#133]
_From @udinachmany on July 3, 2017 14:5_

## Summary

On https://partners.ubuntu.com/find-a-partner?programme=certified-public-cloud for some reason, updating cloud.ca pushed them to the end, in an alphabetised list

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

_Copied from original issue: canonical-websites/www.ubuntu.com#2034_

**Comment by pmahnke** [comment]
@udinachmany I think it is in alpha order, but upper case then lower case... I will look into this.

**Comment by deadlight** [comment]
A fix to this issue has been released
