### ISSUE TITLE
Report a bug redirects to launchpad.net

### ISSUE THREAD

**Issue by tbille** [canonical-websites/partners.ubuntu.com#140]
## Summary

`Report a bug on this site` should redirect to github issues

## Process

- `./run`
- [0.0.0.0:8003](http://0.0.0.0:8003)
- go to the bottom of the page
- click on report a bug

## Actual behavior
`Report a bug on this site` link redirects to launchpad

## Expected behavior
`Report a bug on this site` link redirects to a new github issue on the project

**Comment by anthonydillon** [comment]
Another great spot. Thanks for filing.
