### ISSUE TITLE
Wrong position images

### ISSUE THREAD

**Issue by tbille** [canonical-websites/partners.ubuntu.com#141]
## Summary

The position of the images of the sections `World leaders in the cloud`  and  `Driving innovation in IoT and on PCs` are to height

## Process
- `./run`
- [0.0.0.0:8003](http://0.0.0.0:8003/)

## Current and expected result

Expect the images to be at vertically centered in each sections

## Screenshot

![screenshot-2017-10-11 ubuntu partners](https://user-images.githubusercontent.com/2707508/31448871-635d73fa-ae9d-11e7-8d8e-cdfb592cf656.png)

**Comment by anthonydillon** [comment]
Thanks @tbille, great spot.

**Comment by frankiegranato** [comment]
Looks fine on my browser (chrome).

**Comment by shivjoshi1996** [comment]
After speaking to @tbille, confirmed the issue was on Firefox, and now it seems to have been fixed.
