### ISSUE TITLE
Update assets links to v1

### ISSUE THREAD

**Issue by tbille** [canonical-websites/partners.ubuntu.com#142]
## Summary

A lot of links still use the old version of the assets server url, update all the links to the v1 asset links

## Example

- `https://assets.ubuntu.com/sites/ubuntu/latest/u/img/logos/logo-ubuntu-orange.svg`
Becomes
- `https://assets.ubuntu.com/v1/c6679b95-logo-ubuntu-orange.svg`
In the code : `{{ ASSET_URL_SERVER }}c6679b95-logo-ubuntu-orange.svg`

**Comment by Caleb-Ellis** [comment]
This was fixed in https://github.com/canonical-websites/partners.ubuntu.com/pull/144
