### ISSUE TITLE
Raise a bug link does not point to github

### ISSUE THREAD

**Issue by campbieil** [canonical-websites/partners.ubuntu.com#154]
## Summary
The link to raise a bug on https://partners.ubuntu.com/programmes/hardware links to launchpad not github

## Process
Go to 
https://partners.ubuntu.com/programmes/hardware

Go to bottom of the page and click report a bug

## Current and expected result

Goes to launchpad when it should go to https://github.com/canonical-websites/partners.ubuntu.com/issues/new

## Screenshot

![image](https://user-images.githubusercontent.com/230348/40673458-c6b81dfc-6369-11e8-8cd4-2489d82e39fa.png)

**Comment by anthonydillon** [comment]
This has been updated.
